version: "3.9"

services:
  db:
    image: ankane/pgvector:latest
    restart: always
    environment:
      POSTGRES_DB: forgefleet
      POSTGRES_USER: ff
      POSTGRES_PASSWORD: ffpass
    volumes: [db_data:/var/lib/postgresql/data]

  redis:
    image: redis:7-alpine
    restart: always

  orchestrator:
    build: ../orchestrator        # Dockerfile lives there (next step)
    restart: always
    env_file: ../.env
    depends_on: [db, redis]

  ui:
    build: ../ui
    restart: always
    env_file: ../.env
    depends_on: [orchestrator]
    expose: ["8000"]

  caddy:
    image: caddy:2-alpine
    restart: always
    ports: ["80:80", "443:443"]
    volumes:
      - ../Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
    depends_on: [ui]

volumes:
  db_data:
  caddy_data:
