# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: devtools.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'devtools.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64\x65vtools.proto\"\x1b\n\x0cShellRequest\x12\x0b\n\x03\x63md\x18\x01 \x01(\t\"B\n\rShellResponse\x12\x0e\n\x06stdout\x18\x01 \x01(\t\x12\x0e\n\x06stderr\x18\x02 \x01(\t\x12\x11\n\texit_code\x18\x03 \x01(\x05\"1\n\x10WriteFileRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"\x1f\n\x11WriteFileResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x32i\n\x08\x44\x65vTools\x12)\n\x08RunShell\x12\r.ShellRequest\x1a\x0e.ShellResponse\x12\x32\n\tWriteFile\x12\x11.WriteFileRequest\x1a\x12.WriteFileResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'devtools_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SHELLREQUEST']._serialized_start=18
  _globals['_SHELLREQUEST']._serialized_end=45
  _globals['_SHELLRESPONSE']._serialized_start=47
  _globals['_SHELLRESPONSE']._serialized_end=113
  _globals['_WRITEFILEREQUEST']._serialized_start=115
  _globals['_WRITEFILEREQUEST']._serialized_end=164
  _globals['_WRITEFILERESPONSE']._serialized_start=166
  _globals['_WRITEFILERESPONSE']._serialized_end=197
  _globals['_DEVTOOLS']._serialized_start=199
  _globals['_DEVTOOLS']._serialized_end=304
# @@protoc_insertion_point(module_scope)
